name: Release to production

on:
  push:
    tags:
      - "v*"

jobs:
  build_unix:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, i386, arm64, armhf, riscv64]

    steps:
      - uses: actions/checkout@v2

      - name: Prepare build
        run: ./util/build-prepare.sh

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"

      - name: Build C++
        run: ./util/build-cmake.sh ${{matrix.arch}} unix

      - name: Build CLI
        run: ./util/build-cli.sh ${{matrix.arch}} unix

      - name: Build tar
        run: ./util/package-unix.sh ${{matrix.arch}} tar

      - name: Build deb
        run: ./util/package-unix.sh ${{matrix.arch}} deb

      - name: Build rpm
        run: ./util/package-unix.sh ${{matrix.arch}} rpm

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: ./build/release/
          if-no-files-found: error

  build_windows:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare build
        run: ./util/build-prepare.sh

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"

      - name: Build C++
        run: ./util/build-cmake.sh win64 windows

      - name: Build CLI
        run: ./util/build-cli.sh win64 windows

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: ./build/release/
          if-no-files-found: error

  build_windows_installer:
    needs: build_windows

    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Fetch artifacts
        uses: actions/download-artifact@v3
        with:
          name: packages

      - name: Copy .exe and license to installer dir
        run: |
          copy husarnet-daemon-windows-win64.exe platforms\windows\husarnet-daemon.exe
          copy husarnet-windows-win64.exe platforms\windows\husarnet.exe
          copy LICENSE.txt platforms\windows
        shell: cmd

      - name: Building the installer
        run: |
          "%programfiles(x86)%\Inno Setup 6\iscc.exe" platforms\windows\script.iss
        shell: cmd

      - name: Upload installer
        uses: actions/upload-artifact@v3
        with:
          name: windows_installer
          path: platforms\windows\Output\husarnet-setup.exe

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare tests
        run: ./util/test-prepare.sh

      - name: Build UTs
        run: ./util/test-unit-build.sh

      - name: Run UTs
        run: ./util/test-unit-run.sh

      # - name: Run static analysis (cppcheck)
      #   run: ./util/test-cppcheck.sh

  release_github:
    needs: [test, build_unix, build_windows_installer]

    runs-on: ubuntu-latest

    steps:
      - name: Fetch linux packages
        uses: actions/download-artifact@v3
        with:
          name: packages

      - name: Fetch windows installer
        uses: actions/download-artifact@v3
        with:
          name: windows_installer

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: false
          automatic_release_tag: ${{ github.ref_name }}
          files: |
            *.deb
            *.tar
            *.rpm
            *.exe

  release_prod:
    needs: [test, build_unix, build_windows_installer]

    runs-on: [self-hosted, linux, prod]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Fetch artifacts
        uses: actions/download-artifact@v3
        with:
          name: packages

      - name: Fetch windows installer
        uses: actions/download-artifact@v3
        with:
          name: windows_installer

      - name: Deploy to main Husarnet repository
        run: ./util/deploy.sh main

  build_docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - arch: linux/amd64
            arch_alias: amd64
          - arch: linux/arm64/v8
            arch_alias: arm64
          - arch: linux/arm/v7
            arch_alias: armhf

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.HNETUSER_DOCKERHUB_LOGIN }}
          password: ${{ secrets.HNETUSER_DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./platforms/docker/Dockerfile
          platforms: ${{matrix.arch}}
          push: true
          tags: husarnet/husarnet:${{matrix.arch_alias}}

  release_docker:
    needs: [test, build_docker]

    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.HNETUSER_DOCKERHUB_LOGIN }}
          password: ${{ secrets.HNETUSER_DOCKERHUB_PASSWORD }}

      - name: create manifest
        run: >
          docker manifest create husarnet/husarnet:latest
          --amend husarnet/husarnet:amd64
          --amend husarnet/husarnet:arm64
          --amend husarnet/husarnet:armhf

      - name: push manifest
        run: docker manifest push husarnet/husarnet:latest
