name: Build & test

on:
  pull_request:
    branches: [master]

# When changing steps remember to sync the steps with the other YAMLs
jobs:
  format_code:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Prepare formatting tools
        run: ./util/format-prepare.sh

      - name: Format code
        run: ./util/format.sh

  build_unix:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, i386, arm64, armhf, riscv64]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Prepare build
        run: ./util/build-prepare.sh

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"

      - name: Build C++
        run: ./util/build-cmake.sh ${{matrix.arch}} unix

      - name: Build CLI
        run: ./util/build-cli.sh ${{matrix.arch}} unix

      - name: Build tar
        run: ./util/package-unix.sh ${{matrix.arch}} tar

      - name: Build deb
        run: ./util/package-unix.sh ${{matrix.arch}} deb

      - name: Build rpm
        run: ./util/package-unix.sh ${{matrix.arch}} rpm

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: ./build/release/
          if-no-files-found: error

  build_windows:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Prepare build
        run: ./util/build-prepare.sh

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"

      - name: Build C++
        run: ./util/build-cmake.sh win64 windows

      - name: Build CLI
        run: ./util/build-cli.sh win64 windows

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: ./build/release/
          if-no-files-found: error

  build_windows_installer:
    needs: build_windows

    runs-on: windows-2019

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Fetch artifacts
        uses: actions/download-artifact@v3
        with:
          name: packages

      - name: Copy .exe and license to installer dir
        run: |
          copy husarnet-daemon-windows-win64.exe platforms\windows\husarnet-daemon.exe
          copy husarnet-windows-win64.exe platforms\windows\husarnet.exe
          copy LICENSE.txt platforms\windows
        shell: cmd

      - name: Building the installer
        run: |
          "%programfiles(x86)%\Inno Setup 6\iscc.exe" platforms\windows\script.iss
        shell: cmd

      - name: Upload installer
        uses: actions/upload-artifact@v3
        with:
          name: windows_installer
          path: platforms\windows\Output\husarnet-setup.exe

  build_docker:
    needs: [build_unix]

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - arch: linux/amd64
            arch_alias: amd64
          - arch: linux/arm64/v8
            arch_alias: arm64
          - arch: linux/arm/v7
            arch_alias: armhf

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Fetch artifacts
        uses: actions/download-artifact@v3
        with:
          name: packages

      - name: Move build artifacts in an expected place
        run: cp husarnet* build/release/

      - name: Prepare build artifact aliases
        run: ./util/docker-prepare-paths.sh ${{matrix.arch_alias}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./platforms/docker/Dockerfile
          platforms: ${{matrix.arch}}

  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Prepare tests
        run: ./util/test-prepare.sh

      - name: Run all tests
        run: ./util/test-all.sh
